#!/usr/bin/env bash
set -e -o pipefail

basedir=$(cd "$(dirname "$0")" && pwd -P)
builddir=$basedir/.build

die() { local exitcode=$1; shift; echo -e 1>&2 "$@"; exit $exitcode; }

winvsconfig() {
    #   Use CMake from VS 2017 Professional or Community Edition, if installed.
    local vsprogramfiles="/c/Program Files (x86)/Microsoft Visual Studio/"
    local vsinstalldir="$vsprogramfiles/2017/Professional"
    [[ -d $vsinstalldir ]] || vsinstalldir="$vsprogramfiles/2017/Community"
    local vstools="$vsinstalldir/Common7/IDE/CommonExtensions/Microsoft/CMake/"
    local vscmakebin="$vstools/CMake/bin"
    local vsninjabin="$vstools/Ninja"
    [ -d "$vscmakebin" ] || return 0
    PATH="$vscmakebin:$vsninjabin:$PATH"
    declare -g generator platform config
    if [[ $generator != Ninja ]]; then
        platform=x64
        #   We do this because the default "Debug" debug config
        #   wants to link to python36_d.lib, which doesn't seem to be
        #   supplied with a standard Python install.
        config=RelWithDebInfo
    fi
    return 0
}

check_install_cmake() {
    local minorver
    type cmake >/dev/null 2>&1 \
        && minorver=$(cmake -P "$basedir/libcmake/version_check.cmake")
    minorver="${minorver#-- }"   # Remove leading crud
    [[ -n $minorver && $minorver -ge 12 ]] && return 0
    [[ $(uname -s) = Linux && $(uname -m) = x86_64 ]] || die 3 \
        "No/old cmake and not on Linux x86_64; install cmake >= 3.12."

    local cmver=3.12.4
    local cmtar="cmake-$cmver-Linux-x86_64.tar.gz"
    local cmurl="https://github.com/Kitware/CMake/releases/download/v$cmver/$cmtar"
    local cachedir="$basedir/.dlcache"

    mkdir -p "$cachedir"
    [[ -s $cachedir/$cmtar ]] || {
        echo "== Downloading $cmtar"
        curl -L -o "$cachedir/$cmtar" "$cmurl"
    }
    local cmdest="$builddir/cmake-$cmver-Linux-x86_64"
    [[ -d $cmdest && -x $cmdest/bin/cmake ]] || {
        echo "== Installing $cmtar"
        tar -C "$builddir" -xf "$cachedir/$cmtar"
    }
    PATH="$cmdest/bin:$PATH"
}

target=''
generator=''
platform=''     # Used for Windows
config=''
quiet=1
while true; do case "$1" in
    --)     shift; break;;              # Remaining args not for this script.
    -C)     shift; rm -rf "$builddir";;
    -n)     shift; generator=Ninja;;    # Force Ninja generator
    -t)     shift; target="--target $1"; shift;;    # BUG: no spaces in target
    -v)     shift; unset quiet;;
    *)      break;;
esac; done
#   We do not currently handle extra args because we've not decided
#   to which tool (cmake or native build tool) to pass them.
[[ -n $1 ]] && die 2 "ERROR: Additional tool arguments not yet allowed:" "$@"

mkdir -p "$builddir"
cd "$builddir"
winvsconfig
check_install_cmake || die 3 "ERROR: Can't find/install cmake."
{
    cmake -Wdev -Wdeprecated \
        ${generator:+-G "$generator"} ${platform:+-A "$platform"} \
        .. \
    && cmake --build . ${config:+--config "$config"} $target -- \
    && ctest --output-on-failure ${quiet:+-Q} ${config:+-C "$config"}
}   || die $? "\nFAILED"
